# SPDX-FileCopyrightText: 2026 calibancode
# SPDX-License-Identifier: CC0-1.0

version = 1

[[annotations]]
path = "README.md"
SPDX-FileCopyrightText = "2026 calibancode"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = "screenshots/**"
SPDX-FileCopyrightText = "2026 calibancode"
SPDX-License-Identifier = "CC-BY-SA-4.0"

[[annotations]]
path = "po/**"
SPDX-FileCopyrightText = "2026 calibancode"
SPDX-License-Identifier = "GPL-3.0-or-later"
